<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find rotors_description)/urdf/manipulator_snippets.xacro" />

  <xacro:property name="r1_width" value="0.04"/>
  <xacro:property name="r1_height" value="0.008"/>
  <xacro:property name="r1_length" value="0.24"/>

  <xacro:property name="r2_width" value="0.04"/>
  <xacro:property name="r2_height" value="0.008"/>
  <xacro:property name="r2_length" value="0.35"/>

  <xacro:property name="r3_width" value="0.04"/>
  <xacro:property name="r3_height" value="0.0015"/>
  <xacro:property name="r3_length" value="0.14"/>
  <xacro:property name="center_to_center_length" value="0.1"/>

  <xacro:property name="end_effector_length_back" value="0.105"/>
  <xacro:property name="end_effector_length_front" value="0.12"/>
  <xacro:property name="end_effector_length" value="0.225"/>
  <xacro:property name="end_effector_width" value="0.025"/>
  <xacro:property name="end_effector_height" value="0.007"/>
  <xacro:property name="end_effector_angle" value="-0.52"/>


  <xacro:property name="generic_servo_inertial">
    <inertial>
    <mass value="0.070"/>
    <inertia ixx="0.001" ixy="0.0" ixz="0.0"
    iyy="0.001" iyz="0.0"
    izz="0.001"/>
  </inertial>
  </xacro:property>

  <xacro:property name="r3_frame">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="r3_inertial">
    <mass value="0.001"/>
    <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
    iyy="0.0001" iyz="0.0"
    izz="0.0001"/>
  </xacro:property>

  <xacro:property name="r3_geometry">
    <geometry>
       <box size="${r3_length} ${r3_width} ${r3_height}"/>
    </geometry>
  </xacro:property>

  <xacro:property name="r3_material">
    <material name="orange"/>
  </xacro:property>

  <xacro:property name="r2_frame">
    <origin xyz="${r2_length/2} 0 0" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="r2_inertial">
    <mass value="0.0015"/>
    <inertia ixx="0.00000229511" ixy="0.0" ixz="0.00000000098"
    iyy="0.00018644679" iyz="0.0"
    izz="0.00018419229"/>
  </xacro:property>

  <xacro:property name="r2_geometry">
    <geometry>
       <box size="${r2_length} ${r2_width} ${r2_height}"/>
    </geometry>
  </xacro:property>

  <xacro:property name="r2_material">
    <material name="orange"/>
  </xacro:property>

  <xacro:property name="r1_frame">
    <origin xyz="${r1_length/2} 0 0" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="r1_inertial">
    <mass value="0.0012"/>
    <inertia ixx="0.00000948062" ixy="0.0" ixz="-0.00001716204"
    iyy="0.0000730949" iyz="0.0"
    izz="0.00006364922"/>
  </xacro:property>

  <xacro:property name="r1_geometry">
    <geometry>
       <box size="${r1_length} ${r1_width} ${r1_height}"/>
    </geometry>
  </xacro:property>

  <xacro:property name="r1_material">
    <material name="orange"/>
  </xacro:property>

  <xacro:property name="end_effector_frame">
    <origin xyz="${end_effector_length_back} 0 0" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="end_effector_inertial">
    <mass value="0.001"/>
    <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
    iyy="0.0001" iyz="0.0"
    izz="0.0001"/>
  </xacro:property>

  <xacro:property name="end_effector_geometry">
    <geometry>
       <box size="${end_effector_length} ${end_effector_width} ${end_effector_height}"/>
    </geometry>
  </xacro:property>

<!-- 
#########################################################################################################################
Delta manipulator macro:

#########################################################################################################################
-->

  <xacro:macro name="delta_manipulator_macro"
    params="namespace parent_link *origin">

    <xacro:revolute_joint_macro
      namespace="${namespace}"
      joint_name="${namespace}/pitching"
      parent_link="${namespace}/r0"
      child_link="${namespace}/r3"
      axis="1 0 0"
      friction="0"
      damping="0.1">
      <origin xyz="0 0 -0.05" rpy="0 0 0"/>
    </xacro:revolute_joint_macro>

    <joint name="my_joint" type="floating">
        <parent link="${parent_link}"/>
        <child link="${namespace}/r0"/>
        <xacro:insert_block name="origin" />
        <dynamics damping="0.0" friction="0.0"/>
     </joint>

  <!-- Here we define base link of closed kinematic chain -->

  <link name="${namespace}/r0">
   <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
         <mesh filename="package://rotors_description/meshes/delta_arm_meshes/pitching_base.dae" scale="0.001 0.001 0.001" />
     </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <mesh filename="package://rotors_description/meshes/delta_arm_meshes/pitching_base.dae" scale="0.001 0.001 0.001" />
        </geometry>
    </visual>

    <inertial>
      <xacro:insert_block name="r3_frame"/>
      <xacro:insert_block name="r3_inertial"/>
    </inertial>
  </link>

  <link name="${namespace}/r3">
   <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
         <mesh filename="package://rotors_description/meshes/delta_arm_meshes/pitching_base.dae" scale="0.001 0.001 0.001" />
     </geometry>
    </collision>

    <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://rotors_description/meshes/delta_arm_meshes/pitching_base.dae" scale="0.001 0.001 0.001" />
            </geometry>
    </visual>

    <inertial>
      <xacro:insert_block name="r3_frame"/>
      <xacro:insert_block name="r3_inertial"/>
    </inertial>
  </link>

  <link name="${namespace}/r1_left">
   <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
         <mesh filename="package://rotors_description/meshes/delta_arm_meshes/R1_v2_left.dae" scale="0.001 0.001 0.001" />
     </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://rotors_description/meshes/delta_arm_meshes/R1_v2_left.dae" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>

    <inertial>
      <xacro:insert_block name="r1_frame"/>
      <xacro:insert_block name="r1_inertial"/>
    </inertial>
  </link>

  <link name="${namespace}/r1_right">
   <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
        <mesh filename="package://rotors_description/meshes/delta_arm_meshes/R1_v2.dae" scale="0.001 0.001 0.001" />
    </geometry>
    </collision>

    <visual>
       <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://rotors_description/meshes/delta_arm_meshes/R1_v2.dae" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>

    <inertial>
      <xacro:insert_block name="r1_frame"/>
      <xacro:insert_block name="r1_inertial"/>
    </inertial>
  </link>

  <link name="${namespace}/r2_left">
   <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
         <mesh filename="package://rotors_description/meshes/delta_arm_meshes/R2_v2.dae" scale="0.001 0.001 0.001" />
     </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://rotors_description/meshes/delta_arm_meshes/R2_v2.dae" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>

    <inertial>
      <xacro:insert_block name="r2_frame"/>
      <xacro:insert_block name="r2_inertial"/>
    </inertial>
  </link>

  <link name="${namespace}/r2_right">
   <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
         <mesh filename="package://rotors_description/meshes/delta_arm_meshes/R2_v2.dae" scale="0.001 0.001 0.001" />
     </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://rotors_description/meshes/delta_arm_meshes/R2_v2.dae" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>

    <inertial>
      <xacro:insert_block name="r2_frame"/>
      <xacro:insert_block name="r2_inertial"/>
    </inertial>
  </link>

  <link name="${namespace}/end_effector">
   <collision>
     <origin xyz="-0.105 0.0125 0" rpy="1.57 0 0"/>
     <geometry>
         <mesh filename="package://rci_description/meshes/Connector_v3.dae.dae" scale="0.001 0.001 0.001" />
     </geometry>
    </collision>

    <visual>
      <origin xyz="-0.105 0.0125 0" rpy="1.57 0 0"/>
      <geometry>
          <mesh filename="package://rci_description/meshes/Connector_v3.dae" scale="0.001 0.001 0.001" />
      </geometry>

    </visual>

    <inertial>
      <xacro:insert_block name="end_effector_frame"/>
      <xacro:insert_block name="end_effector_inertial"/>
    </inertial>
  </link>

  <link name="${namespace}/temp">
   <collision>
     <origin xyz="0 0 -0.008" rpy="0 0 0"/>
     <geometry>
			<cylinder length="0.016"  radius="0.03"/>
     </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 -0.008" rpy="0 0 0"/>
      <geometry>
          <cylinder length="0.016"  radius="0.03"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <xacro:insert_block name="end_effector_inertial"/>
    </inertial>
  </link>
  <gazebo reference="${namespace}/temp">
    	<material>Gazebo/White</material>
  </gazebo>

<!-- Define joints -->
  <xacro:revolute_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/left_1"
    parent_link="${namespace}/r3"
    child_link="${namespace}/r1_left"
    axis="0 0 1"
    friction="0"
    damping="0.1">
    <origin xyz="${-center_to_center_length/2} 0 -0.005" rpy="0 0 0"/>
  </xacro:revolute_joint_macro>

  <xacro:revolute_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/right_1"
    parent_link="${namespace}/r3"
    child_link="${namespace}/r1_right"
    axis="0 0 1"
    friction="0"
    damping="0.1">
    <origin xyz="${center_to_center_length/2} 0 -0.005" rpy="0 0 0"/>
  </xacro:revolute_joint_macro>

  <xacro:revolute_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/left_2"
    parent_link="${namespace}/r1_left"
    child_link="${namespace}/r2_left"
    axis="0 0 1"
    friction="0"
    damping="0.1">
    <origin xyz="${r1_length} 0 0.01" rpy="0 0 0"/>
  </xacro:revolute_joint_macro>

  <xacro:revolute_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/right_2"
    parent_link="${namespace}/r1_right"
    child_link="${namespace}/r2_right"
    axis="0 0 1"
    friction="0"
    damping="0.1">
    <origin xyz="${r1_length} 0 -0.01" rpy="0 0 0"/>
  </xacro:revolute_joint_macro>

  <xacro:gazebo_revolute_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/closing"
    parent_link="${namespace}/r2_left"
    child_link="${namespace}/r2_right"
    pose="${r2_length} 0 0 0 0 0"
    axis="0 0 1"
    friction="0"
    damping="0.1"
    spring_reference="0"
    spring_stiffness="0"
    lower_limit="-1e+16"
    upper_limit="1e+16"
    effort_limit="1000">
  </xacro:gazebo_revolute_joint_macro>

<!--
	<xacro:revolute_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/end_effector"
    parent_link="${namespace}/r2_left"
    child_link="${namespace}/end_effector"
    axis="0 0 1"
    friction="0"
    damping="0.1">
    <origin xyz="${r2_length} 0 0" rpy="0 0 0"/>
  </xacro:revolute_joint_macro>
-->

  <xacro:fixed_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/end_effector"
    parent_link="${namespace}/r2_right"
    child_link="${namespace}/end_effector">
    <origin xyz="${r2_length} 0 0" rpy="0 0 ${end_effector_angle}"/>
	</xacro:fixed_joint_macro>

  <xacro:fixed_joint_macro
    namespace="${namespace}"
    joint_name="${namespace}/temp"
    parent_link="${namespace}/r2_left"
    child_link="${namespace}/temp">
    <origin xyz="${r2_length} 0 0" rpy="0 0 0"/>
	</xacro:fixed_joint_macro>

  <!-- Attach actuators -->

 <xacro:servo_motor_macro
   namespace="${namespace}"
   motor_name="motor_left"
   parent_link="${namespace}/r3"
   actuated_joint="${namespace}/left_1"
   motor_model="generic_servo1"
   maxTorque="2"
   noLoadSpeed="0.11"
   Kp="30.0"
   Kd="0.05"
   Ki="0.40"
   minAngle="${-pi}"
   maxAngle="${pi}"
	 measurement_divisor="10"
	 measurement_delay="0"
	 unknown_delay="0.0"
	 noise_normal_angle="0.0"
	 noise_normal_angular_velocity="0.0"
 	 noise_normal_torque="0.0"
	 noise_uniform_angle="0.0"
	 noise_uniform_angular_velocity="0.0"
	 noise_uniform_torque="0.0"
   enable_visual="true"
   visual_scale="1"
   color="Blue">
   <origin xyz="${center_to_center_length/2} 0 0" rpy="0 0 0"/>
   <xacro:insert_block name="generic_servo_inertial"/>
 </xacro:servo_motor_macro>

 <xacro:servo_motor_macro
   namespace="${namespace}"
   motor_name="motor_right"
   parent_link="${namespace}/r3"
   actuated_joint="${namespace}/right_1"
   motor_model="generic_servo2"
   maxTorque="2"
   noLoadSpeed="0.11"
   Kp="30.0"
   Kd="0.05"
   Ki="0.40"
   minAngle="${-pi}"
   maxAngle="${pi}"
	 measurement_divisor="10"
	 measurement_delay="0"
	 unknown_delay="0.0"
	 noise_normal_angle="0.0"
	 noise_normal_angular_velocity="0.0"
 	 noise_normal_torque="0.0"
	 noise_uniform_angle="0.0"
	 noise_uniform_angular_velocity="0.0"
	 noise_uniform_torque="0.0"
   enable_visual="true"
   visual_scale="1"
   color="Red">
   <origin xyz="${-center_to_center_length/2} 0 0" rpy="0 0 0"/>
   <xacro:insert_block name="generic_servo_inertial"/>
 </xacro:servo_motor_macro>

 <xacro:servo_motor_macro
   namespace="${namespace}"
   motor_name="motor_pitching"
   parent_link="${namespace}/r0"
   actuated_joint="${namespace}/pitching"
   motor_model="generic_servo0"
   maxTorque="2"
   noLoadSpeed="0.11"
   Kp="30.0"
   Kd="0.05"
   Ki="0.40"
   minAngle="${-pi}"
   maxAngle="${pi}"
	 measurement_divisor="10"
	 measurement_delay="0"
	 unknown_delay="0.0"
	 noise_normal_angle="0.0"
	 noise_normal_angular_velocity="0.0"
 	 noise_normal_torque="0.0"
	 noise_uniform_angle="0.0"
	 noise_uniform_angular_velocity="0.0"
	 noise_uniform_torque="0.0"
   enable_visual="true"
   visual_scale="1"
   color="Green">
   <origin xyz="0 0.02 -0.02" rpy="0 1.57 0"/>
   <xacro:insert_block name="generic_servo_inertial"/>
 </xacro:servo_motor_macro>

<!--TODO: replace this servo motor with a stereo camera, is only a stand in to get position info of endeffector -->
 <xacro:servo_motor_macro
   namespace="${namespace}"
   motor_name="motor_end_effector"
   parent_link="${namespace}/end_effector"
   actuated_joint="${namespace}/end_effector"
   motor_model="generic_servo3"
   maxTorque="0"
   noLoadSpeed="0.11"
   Kp="0.0"
   Kd="0.0"
   Ki="0.0"
   minAngle="${-pi}"
   maxAngle="${pi}"
	 measurement_divisor="10"
	 measurement_delay="0"
	 unknown_delay="0.0"
	 noise_normal_angle="0.0"
	 noise_normal_angular_velocity="0.0"
 	 noise_normal_torque="0.0"
	 noise_uniform_angle="0.0"
	 noise_uniform_angular_velocity="0.0"
	 noise_uniform_torque="0.0"
   enable_visual="true"
   visual_scale="0.2"
   color="Blue">
   <origin xyz="${end_effector_length_front} 0 ${end_effector_height/2}" rpy="0 0 0"/>
   <inertial>
    <mass value="0.00001"/>
    <inertia ixx="0.00001" ixy="0.0" ixz="0.0"
    iyy="0.00001" iyz="0.0"
    izz="0.00001"/>
  </inertial>
 </xacro:servo_motor_macro>

<!-- Initial configuration plugin -->
<gazebo>
  <plugin name="initial_configuration" filename="librotors_gazebo_robot_initial_configuration_plugin.so">
    <robotNamespace>${namespace}</robotNamespace>
 <initial_configuration>
   <config joint_name="left_1"  initial_position="2.488"/>
   <config joint_name="left_2"  initial_position="-1.676"/>
   <config joint_name="right_1" initial_position="0.653"/>
   <config joint_name="right_2" initial_position="1.676"/>
 </initial_configuration>
 <loop_closure_joints>
   <joint joint_name="closing"/>
 </loop_closure_joints>
 </plugin>
</gazebo>

<!-- 6DoF shock absorber plugin -->
<gazebo>
  <plugin name="6dof_shock_absorber" filename="librotors_gazebo_six_dof_shock_absorber_plugin.so">
    <robotNamespace>${namespace}</robotNamespace>
    <ParentLinkName>${parent_link} </ParentLinkName>
    <ChildLinkName>${namespace}/r0 </ChildLinkName>
    <translational_spring_constant>20 20 100</translational_spring_constant>
    <translational_damper_constant>5 5 20</translational_damper_constant>
    <rotational_spring_constant>8 15 8</rotational_spring_constant>
    <rotational_damper_constant>1 1 1</rotational_damper_constant>
 </plugin>
</gazebo>

</xacro:macro>

</robot>
